name: Terraform Module integration test

on:
  push:
    branches:
      - master
jobs:
  validate:
    name: Test Module and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Get Go dependencies
        run: go get -v -t -d ./...

      - name: Run Tests
        working-directory: "CHAP05/testing-terratest/module/tests/"
        run: |
          go test -v -timeout 30m

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
